[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
weft = "HBLZDwAjPKnmZ6KW1ah4qC7yMTysbpSrC5fUW98cJ1md"

[programs.localnet]
weft = "HBLZDwAjPKnmZ6KW1ah4qC7yMTysbpSrC5fUW98cJ1md"

[programs.mainnet]
weft = "HBLZDwAjPKnmZ6KW1ah4qC7yMTysbpSrC5fUW98cJ1md"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
