// Weft SDK entry point.
//
// Per-program clients are generated from on-chain IDLs into ./generated by
// `pnpm generate` (Codama).

export const SDK_VERSION = '0.1.0';

// Mainnet deploy surface: one on-chain program with many instructions.
export * as weft from './generated/weft/src/generated';

// Off-chain reward/settlement math, byte-identical to the on-chain program.
export * as math from './math';
