// Weft SDK entry point.
//
// Per-program clients are generated from on-chain IDLs into ./generated by
// `pnpm generate` (Codama). Re-exports are wired up here as each program's IDL
// lands, starting in M1 (weft-vesting / $WEFT token).

export const SDK_VERSION = '0.1.0';
